services:

  mariadb:
    image: mariadb:11
    container_name: mon_mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: projet
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db/data:/var/lib/mysql

  php:
    build:
      context: ./php
      dockerfile: dockerfile
    container_name: mon_php
    restart: always
    ports:
      - "80:80"
    environment:
      API_URL: http://localhost:9000
      ONESIGNAL_APP_ID: ${ONESIGNAL_APP_ID}
    volumes:
      - ./upload:/var/www/html/upload
    depends_on:
      - mariadb

  go:
    build: ./go
    container_name: mon_go
    restart: always
    ports:
      - "9000:9000"
    environment:
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
      STRIPE_WEBHOOK_SECRET: ${STRIPE_WEBHOOK_SECRET}
      STRIPE_PRICE_ID_MOIS: ${STRIPE_PRICE_ID_MOIS}
      STRIPE_PRICE_ID_AN: ${STRIPE_PRICE_ID_AN}
      APP_BASE_URL: ${APP_BASE_URL}
      ONESIGNAL_APP_ID: ${ONESIGNAL_APP_ID}
      ONESIGNAL_REST_API_KEY: ${ONESIGNAL_REST_API_KEY}
    depends_on:
      - mariadb

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: mon_phpmyadmin
    restart: always
    environment:
      PMA_HOST: mariadb
      PMA_USER: root
      PMA_PASSWORD: root
      PMA_DATABASE: projet
    ports:
      - "8081:80"
    depends_on:
      - mariadb

  libretranslate:
    image: libretranslate/libretranslate:latest
    container_name: mon_libretranslate
    restart: always
    environment:
      LT_LOAD_ONLY: en,fr,ru,es,de,it,pt,nl,pl,uk
    ports:
      - "5000:5000"

volumes:
  mariadb_data: